"""init all tables

Revision ID: ca6731412840
Revises: a09786152ed8
Create Date: 2025-12-03 21:06:28.038521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca6731412840'
down_revision: Union[str, Sequence[str], None] = 'a09786152ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('category_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_activity_types_category_key'), 'activity_types', ['category_key'], unique=True)
    op.create_index(op.f('ix_activity_types_id'), 'activity_types', ['id'], unique=False)
    op.create_table('organizers',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_organizers_id'), 'organizers', ['id'], unique=False)
    op.create_index(op.f('ix_organizers_status'), 'organizers', ['status'], unique=False)
    op.create_table('super_admins',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_super_admins_email'), 'super_admins', ['email'], unique=True)
    op.create_index(op.f('ix_super_admins_id'), 'super_admins', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('employment', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('activity_templates',
    sa.Column('template_code', sa.String(), nullable=True),
    sa.Column('activity_type_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_uuid'], ['activity_types.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_activity_templates_activity_type_uuid'), 'activity_templates', ['activity_type_uuid'], unique=False)
    op.create_index(op.f('ix_activity_templates_id'), 'activity_templates', ['id'], unique=False)
    op.create_index(op.f('ix_activity_templates_template_code'), 'activity_templates', ['template_code'], unique=True)
    op.create_table('organizer_applications',
    sa.Column('application_uuid', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('organizer_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_uuid', sa.UUID(), nullable=True),
    sa.Column('reviewer_role', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_uuid'], ['organizers.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_organizer_applications_application_uuid'), 'organizer_applications', ['application_uuid'], unique=True)
    op.create_index(op.f('ix_organizer_applications_id'), 'organizer_applications', ['id'], unique=False)
    op.create_index(op.f('ix_organizer_applications_organizer_uuid'), 'organizer_applications', ['organizer_uuid'], unique=False)
    op.create_table('organizer_memberships',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('organizer_uuid', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'editor', 'viewer', 'member', name='organizer_member_roles'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='organizer_member_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_uuid'], ['organizers.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'organizer_uuid', name='uq_user_organizer'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_organizer_memberships_id'), 'organizer_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_organizer_memberships_organizer_uuid'), 'organizer_memberships', ['organizer_uuid'], unique=False)
    op.create_index(op.f('ix_organizer_memberships_user_uuid'), 'organizer_memberships', ['user_uuid'], unique=False)
    op.create_table('system_memberships',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system_admin', 'site_admin', 'support', 'auditor', name='system_roles'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='system_status'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', name='uq_system_user'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_system_memberships_id'), 'system_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_system_memberships_user_uuid'), 'system_memberships', ['user_uuid'], unique=False)
    op.create_table('events',
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('organizer_uuid', sa.UUID(), nullable=False),
    sa.Column('activity_template_uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_template_uuid'], ['activity_templates.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_uuid'], ['organizers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_events_activity_template_uuid'), 'events', ['activity_template_uuid'], unique=False)
    op.create_index(op.f('ix_events_event_code'), 'events', ['event_code'], unique=True)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_organizer_uuid'), 'events', ['organizer_uuid'], unique=False)
    op.create_table('template_fields',
    sa.Column('template_uuid', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_uuid'], ['activity_templates.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_template_fields_id'), 'template_fields', ['id'], unique=False)
    op.create_index(op.f('ix_template_fields_template_uuid'), 'template_fields', ['template_uuid'], unique=False)
    op.create_table('event_fields',
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('placeholder', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_uuid'], ['events.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_uuid', 'field_key', name='uix_event_field'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_event_fields_event_uuid'), 'event_fields', ['event_uuid'], unique=False)
    op.create_index(op.f('ix_event_fields_field_key'), 'event_fields', ['field_key'], unique=False)
    op.create_index(op.f('ix_event_fields_id'), 'event_fields', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_code', sa.String(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_uuid'], ['events.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_submissions_event_uuid'), 'submissions', ['event_uuid'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_submission_code'), 'submissions', ['submission_code'], unique=True)
    op.create_index(op.f('ix_submissions_user_email'), 'submissions', ['user_email'], unique=False)
    op.create_index(op.f('ix_submissions_user_uuid'), 'submissions', ['user_uuid'], unique=False)
    op.create_table('submission_values',
    sa.Column('submission_uuid', sa.UUID(), nullable=False),
    sa.Column('event_field_uuid', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_file', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_field_uuid'], ['event_fields.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_uuid'], ['submissions.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_submission_values_event_field_uuid'), 'submission_values', ['event_field_uuid'], unique=False)
    op.create_index(op.f('ix_submission_values_id'), 'submission_values', ['id'], unique=False)
    op.create_index(op.f('ix_submission_values_submission_uuid'), 'submission_values', ['submission_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_values_submission_uuid'), table_name='submission_values')
    op.drop_index(op.f('ix_submission_values_id'), table_name='submission_values')
    op.drop_index(op.f('ix_submission_values_event_field_uuid'), table_name='submission_values')
    op.drop_table('submission_values')
    op.drop_index(op.f('ix_submissions_user_uuid'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_user_email'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submission_code'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_event_uuid'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_event_fields_id'), table_name='event_fields')
    op.drop_index(op.f('ix_event_fields_field_key'), table_name='event_fields')
    op.drop_index(op.f('ix_event_fields_event_uuid'), table_name='event_fields')
    op.drop_table('event_fields')
    op.drop_index(op.f('ix_template_fields_template_uuid'), table_name='template_fields')
    op.drop_index(op.f('ix_template_fields_id'), table_name='template_fields')
    op.drop_table('template_fields')
    op.drop_index(op.f('ix_events_organizer_uuid'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_code'), table_name='events')
    op.drop_index(op.f('ix_events_activity_template_uuid'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_system_memberships_user_uuid'), table_name='system_memberships')
    op.drop_index(op.f('ix_system_memberships_id'), table_name='system_memberships')
    op.drop_table('system_memberships')
    op.drop_index(op.f('ix_organizer_memberships_user_uuid'), table_name='organizer_memberships')
    op.drop_index(op.f('ix_organizer_memberships_organizer_uuid'), table_name='organizer_memberships')
    op.drop_index(op.f('ix_organizer_memberships_id'), table_name='organizer_memberships')
    op.drop_table('organizer_memberships')
    op.drop_index(op.f('ix_organizer_applications_organizer_uuid'), table_name='organizer_applications')
    op.drop_index(op.f('ix_organizer_applications_id'), table_name='organizer_applications')
    op.drop_index(op.f('ix_organizer_applications_application_uuid'), table_name='organizer_applications')
    op.drop_table('organizer_applications')
    op.drop_index(op.f('ix_activity_templates_template_code'), table_name='activity_templates')
    op.drop_index(op.f('ix_activity_templates_id'), table_name='activity_templates')
    op.drop_index(op.f('ix_activity_templates_activity_type_uuid'), table_name='activity_templates')
    op.drop_table('activity_templates')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_super_admins_id'), table_name='super_admins')
    op.drop_index(op.f('ix_super_admins_email'), table_name='super_admins')
    op.drop_table('super_admins')
    op.drop_index(op.f('ix_organizers_status'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_id'), table_name='organizers')
    op.drop_table('organizers')
    op.drop_index(op.f('ix_activity_types_id'), table_name='activity_types')
    op.drop_index(op.f('ix_activity_types_category_key'), table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
