"""init enterprise schema

Revision ID: d6d4e0f555b8
Revises: 
Create Date: 2025-11-26 18:27:11.427565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d4e0f555b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('category_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_key', 'id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_activity_types_category_key'), 'activity_types', ['category_key'], unique=False)
    op.create_index(op.f('ix_activity_types_id'), 'activity_types', ['id'], unique=False)
    op.create_table('organizers',
    sa.Column('organizer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('organizer_id', 'id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_organizers_email'), 'organizers', ['email'], unique=True)
    op.create_index(op.f('ix_organizers_id'), 'organizers', ['id'], unique=False)
    op.create_index(op.f('ix_organizers_organizer_id'), 'organizers', ['organizer_id'], unique=False)
    op.create_table('activity_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('category_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_key'], ['activity_types.category_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_activity_templates_category_key'), 'activity_templates', ['category_key'], unique=False)
    op.create_index(op.f('ix_activity_templates_id'), 'activity_templates', ['id'], unique=False)
    op.create_index(op.f('ix_activity_templates_template_id'), 'activity_templates', ['template_id'], unique=False)
    op.create_table('activity_template_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['activity_templates.template_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_activity_template_fields_id'), 'activity_template_fields', ['id'], unique=False)
    op.create_index(op.f('ix_activity_template_fields_template_id'), 'activity_template_fields', ['template_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.organizer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['activity_templates.template_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id', 'id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_events_template_id'), 'events', ['template_id'], unique=False)
    op.create_table('event_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_event_fields_event_id'), 'event_fields', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_fields_id'), 'event_fields', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', 'id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_submissions_event_id'), 'submissions', ['event_id'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_submission_id'), 'submissions', ['submission_id'], unique=False)
    op.create_table('submission_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('uploaded_file', sa.String(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('created_by_role', sa.String(), nullable=True),
    sa.Column('updated_by_role', sa.String(), nullable=True),
    sa.Column('deleted_by_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_submission_values_id'), 'submission_values', ['id'], unique=False)
    op.create_index(op.f('ix_submission_values_submission_id'), 'submission_values', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_values_submission_id'), table_name='submission_values')
    op.drop_index(op.f('ix_submission_values_id'), table_name='submission_values')
    op.drop_table('submission_values')
    op.drop_index(op.f('ix_submissions_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_event_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_event_fields_id'), table_name='event_fields')
    op.drop_index(op.f('ix_event_fields_event_id'), table_name='event_fields')
    op.drop_table('event_fields')
    op.drop_index(op.f('ix_events_template_id'), table_name='events')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_activity_template_fields_template_id'), table_name='activity_template_fields')
    op.drop_index(op.f('ix_activity_template_fields_id'), table_name='activity_template_fields')
    op.drop_table('activity_template_fields')
    op.drop_index(op.f('ix_activity_templates_template_id'), table_name='activity_templates')
    op.drop_index(op.f('ix_activity_templates_id'), table_name='activity_templates')
    op.drop_index(op.f('ix_activity_templates_category_key'), table_name='activity_templates')
    op.drop_table('activity_templates')
    op.drop_index(op.f('ix_organizers_organizer_id'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_id'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_email'), table_name='organizers')
    op.drop_table('organizers')
    op.drop_index(op.f('ix_activity_types_id'), table_name='activity_types')
    op.drop_index(op.f('ix_activity_types_category_key'), table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
